apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-edge-demo-ui
  name: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-edge-demo-ui
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-edge-demo-ui
    spec:
      containers:
      - image: atgracey/edge-demo-ui:latest
        name: frontend
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: ui
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-edge-demo-ui
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: ui-lb
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-edge-demo-ui
  type: LoadBalancer